#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.6ubuntu2
if [ -x "/etc/init.d/hadoop-yarn-resourcemanager" ]; then
	invoke-rc.d hadoop-yarn-resourcemanager stop || exit 1
fi
# End automatically added section
