#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.6ubuntu2
if [ -x "/etc/init.d/hadoop-hdfs-secondarynamenode" ]; then
	invoke-rc.d hadoop-hdfs-secondarynamenode stop || exit 1
fi
# End automatically added section
